import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, FileText, File } from "lucide-react";
import { Message } from "@/hooks/useChatbot";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface ChatExportProps {
  messages: Message[];
}

export function ChatExport({ messages }: ChatExportProps) {
  const [exporting, setExporting] = useState(false);

  const formatMessagesForExport = () => {
    return messages.map(msg => {
      const time = msg.timestamp.toLocaleString();
      const role = msg.role === "user" ? "You" : "EngageFlow AI";
      return `[${time}] ${role}:\n${msg.content}\n`;
    }).join("\n" + "─".repeat(50) + "\n\n");
  };

  const exportAsTxt = () => {
    if (messages.length === 0) {
      toast.error("No messages to export");
      return;
    }

    const header = `EngageFlow AI Chat Export\nExported: ${new Date().toLocaleString()}\nTotal Messages: ${messages.length}\n\n${"═".repeat(50)}\n\n`;
    const content = header + formatMessagesForExport();
    
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `engageflow-chat-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success("Chat exported as TXT");
  };

  const exportAsPdf = async () => {
    if (messages.length === 0) {
      toast.error("No messages to export");
      return;
    }

    setExporting(true);
    toast.info("Generating PDF...");

    try {
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let yPosition = margin;

      // Header with branding
      pdf.setFontSize(20);
      pdf.setTextColor(0, 0, 0); // Black for branding
      pdf.text("EngageFlow AI", margin, yPosition);
      yPosition += 8;
      
      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text("Powered by FullEnrich API for deep B2B enrichment", margin, yPosition);
      yPosition += 8;

      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text(`Exported: ${new Date().toLocaleString()}`, margin, yPosition);
      yPosition += 5;
      pdf.text(`Total Messages: ${messages.length}`, margin, yPosition);
      yPosition += 15;

      // Divider
      pdf.setDrawColor(200);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Messages
      for (const msg of messages) {
        const isUser = msg.role === "user";
        const time = msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        const role = isUser ? "You" : "EngageFlow AI";

        // Check if we need a new page
        if (yPosition > pageHeight - 40) {
          pdf.addPage();
          yPosition = margin;
        }

        // Role and time
        pdf.setFontSize(10);
        pdf.setTextColor(isUser ? 59 : 34, isUser ? 130 : 197, isUser ? 246 : 94);
        pdf.setFont("helvetica", "bold");
        pdf.text(`${role} • ${time}`, margin, yPosition);
        yPosition += 6;

        // Message content
        pdf.setFontSize(11);
        pdf.setTextColor(50);
        pdf.setFont("helvetica", "normal");
        
        const lines = pdf.splitTextToSize(msg.content, maxWidth);
        for (const line of lines) {
          if (yPosition > pageHeight - 20) {
            pdf.addPage();
            yPosition = margin;
          }
          pdf.text(line, margin, yPosition);
          yPosition += 5;
        }
        
        yPosition += 8;
      }

      // Footer
      const totalPages = pdf.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text(
          `Page ${i} of ${totalPages} • Generated by EngageFlow`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      }

      pdf.save(`engageflow-chat-${new Date().toISOString().slice(0, 10)}.pdf`);
      toast.success("Chat exported as PDF");
    } catch (error) {
      console.error("PDF export failed:", error);
      toast.error("Failed to generate PDF");
    } finally {
      setExporting(false);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="h-8 w-8" disabled={exporting}>
          <Download className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportAsTxt}>
          <FileText className="w-4 h-4 mr-2" />
          Export as TXT
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsPdf}>
          <File className="w-4 h-4 mr-2" />
          Export as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}